baseURL = "https://blog.cottongin.xyz"
title = "my blog"
theme = "hugo-theme-bootstrap"
copyright = "Copyright © {year} cottongin. All Rights Reserved."

# # Multilingual mode
# defaultContentLanguage = "en"
# defaultContentLanguageInSubdir = true

# Pagination
paginate = 10
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
